# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# other options: 'macOS-10.13', 'vs2017-win2016'

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: pwd && ls -la
- script: python ./conf.py

- script: python ./script.py

variables:
- group: emirates-group

- script: echo $hive && echo $pig
