jobs:
- job: first
  variables:
  - group: emirates-group
  - name: job_name
    value: 'Execute step 1'
  steps:
    - script: |
        echo $hive
        echo $pig
      displayName: 'show variable values'

