pool:
  vmImage: 'Ubuntu 16.04'

steps:

  variables:
  - group: variable3
  - name: job_name
    value: 'Build us-east-1'
  steps:
    - script: |
        pwd && ls -la
        echo $(job_name)
        echo $(var1)
      displayName: 'Show Variable Values'


