pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: variable3

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(var1)'


- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'conf.py'