jobs:
- job: build_Virginia
  variables:
  - group: variable3
  - name: job_name
    value: 'Build us-east-1'
  steps:
    - script: |
        pwd && ls -la
        echo $(job_name)
        echo $(var1)
      displayName: 'Show Variable Values'
- job: build_Oregon
  variables:
  - group: emirates-group
  - name: job_name
    value: 'Build us-west-2'
  steps:
    - script: |
        echo $(job_name)
        echo $(hive)
        echo $(pig)
      displayName: 'Show Variable Values'
